services:
  postgres_db:
    image: postgres:15-alpine
    container_name: local_db
    environment:
      db_user: app_user
      db_pass: 123
      db: table_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dataops_worker:
    build: . 
    container_name: pipeline_runner
    environment:
      - URL=postgresql://app_user:pass_123@postgres_db:5432/table_dev
    depends_on:
      - postgres_db

volumes:
  pgdata:



services:
  postgres:
    image: postgres:15-alpine
    environment:
      - user=airfow
      - pass=airfow
      - db=airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data 

  airflow_init:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: db init 

volumes:
  airflow_db: