name: data

on: [pull_request]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
     - name: check code repo
       uses: actions/checkout@v4

     - name: set up python
       uses: actions/setup-python@v5
       with:
        python-version: "3.11"

     - name: install
       run: pip install -r requirements.txt

     - name: run tests
       run: pytest tests/



on:
  push:
    branches: [ main ]
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: run syntax 
        run: | 
          pip install flake8
          flake8 src/ 